language: en
pipeline:
- name: MitieNLP
  model: "data/total_word_feature_extractor_zh.dat"
- name: MitieEntityExtractor
- name: JiebaTokenizer
- name: RegexFeaturizer
- name: MitieFeaturizer
- name: SklearnIntentClassifier
  epochs: 200
  ranking_length: 5
- name: EntitySynonymMapper
- name: ResponseSelector
  retrieval_intent: out_of_scope
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  retrieval_intent: faq
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  retrieval_intent: chitchat
  scale_loss: false
  epochs: 100
- name: FallbackClassifier
  threshold: 0.7
policies:
- name: TEDPolicy
  max_history: 3
  epochs: 20
  batch_size:
  - 32
  - 64
- max_history: 3
  name: AugmentedMemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True